### ISSUE TITLE
Dota2 crash on Linux steam during capture

### ISSUE THREAD

**Issue by mizhen** [LunarG/VulkanTools#94] opened 2016-09-26 19:51 UTC
platform Ubuntu16.04/AMD Fury/Dota2 on steam
launch option: -vconsole -vulkan -vktrace +vulkan_buffer_update_mode 0

crash during capture,  just couple of seconds  after start dota2 from steam client,

**Comment by ardaLunarG** [comment] 2016-10-09 01:00
Ming,
I tried to capture on Linux.
I was able to run Dota2 app w/o steam and trace. However after update steam and dota2, I cannot run Dota2 app w/o steam. When I try to start trace with steam app, trace file only records initial physical device related API's and stop. Probably Dota2 spins off as separate process and I cannot capture.

Can you share your exact steps when you capture Dota2 trace on Linux?

I tried capture Dota2 trace on Windows. As I can run Dota2 w/o steam, I could successfully trace and replay.

**Comment by mizhen** [comment] 2016-10-11 14:41
Hi Arda,

All my test  in this issue base on vktrace server mode and run dota2 on steam(Linux and Windows). 

The steps are same on windows and Linux platform(Ubuntu), first start vktrace server mode on one command line window, then from another command line window, start steam with capture(make sure disable persistent mapped buffer for dota2 in steam launch option), start dota2. For all the two platforms, recent version of vktrace all crash after enter dota2, I also build and test  2016.7.22 commit from Lunarg git repo, no this problem.

I'll test the most recent version of vktrace and get back to you.

Regards
Ming Zheng

**Comment by davidlunarg** [comment] 2016-11-07 23:14
Hi Ming,
Are you running debug or release Vulkan code? I have found that with a debuggable trace layer, attempting to create a dota2 trace results in Dota2 exiting due to a failed assert. If the code is compiled Release, I can successfully create a trace (although I sometimes the vktrace program doesn't exit when Dota2 exits)>

**Comment by eero-t** [comment] 2016-12-15 15:09
Now that DOTA2 has had a major update, maybe this should be set as duplicate of bug #121 ?

**Comment by ardaLunarG** [comment] 2016-12-15 17:56
After Dota2 update trace replay issues filed in:
https://github.com/LunarG/VulkanTools/issues/121

Closing this one as we follow on 121

**Closed by ardaLunarG** 2016-12-15 17:56 UTC
Labels: bug
