### ISSUE TITLE
Build: pthreads with Linux/Cmake 3.5.2 not found

### ISSUE THREAD

**Issue by yousry** [LunarG/VulkanTools#34] opened 2016-04-26 11:22 UTC
My workaround for this problem (Ubuntu cmake package is 3.5.1):

```bash
diff --git a/icd/intel/kmd/CMakeLists.txt b/icd/intel/kmd/CMakeLists.txt
index baeb3e6..a0214f3 100644
--- a/icd/intel/kmd/CMakeLists.txt
+++ b/icd/intel/kmd/CMakeLists.txt
@@ -29,7 +29,11 @@ if(UNIX)
     set_source_files_properties(${libdrm_sources} PROPERTIES COMPILE_FLAGS
         "-std=gnu99 -Wno-type-limits -Wno-unused-variable")
 
-    find_package(PthreadStubs REQUIRED)
+
+set(THREADS_PREFER_PTHREAD_FLAG ON)
+find_package(Threads REQUIRED)
+#    find_package(PthreadStubs REQUIRED)
+
     list(APPEND include_dirs ${PTHREADSTUBS_INCLUDE_DIRS})
     list(APPEND libraries ${PTHREADSTUBS_LIBRARIES})

```

**Comment by karl-lunarg** [comment] 2016-06-03 00:17
I just did a fresh install of Ubuntu 16.04, installed the packages mentioned in BUILDVT.md, and built the VulkanTools repo without any issues.  The cmake version is 3.5.1 and the cmake messages indicate that PthreadStubs, pthread.h, and pthread_create were all successfully found.

I'm going to close this as I do not see any problem.  Please reopen or comment here if you think that a problem still exists.  Please at least explain exactly what the problem is, in addition to posting a solution.  Also please indicate your OS version, etc, that might be useful for explaining and reproducing the problem.

**Closed by karl-lunarg** 2016-06-03 00:17 UTC
Labels: enhancement
