### ISSUE TITLE
api_dump: corrupted dump in multithreaded application.

### ISSUE THREAD

**Issue by dor666** [LunarG/VulkanTools#932] opened 2019-11-19 09:47 UTC
I'm using api_dump with flush option.

I get this in output in multithreaded app:

> Thread 3, Frame 1674:
> vkCmdDispatch(commandBuffer, groupCountX, groupCountY, groupCountZ) returns voidThread 5, Frame 1674:
> vkCmdWriteTimestamp(commandBuffer, pipelineStage, queryPool, query) returns void:
>     commandBuffer:                  VkCommandBuffer = 0000022C02BC9420
>     ...

I guess, this is due to separate head and body of dump are inserted to stream separately. It can be added in a middle of such insertion in another thread.

I would like an option to:
a) print to separate files per thread, or:
b) save a string stream of head and body and send it to output after the api call is finished.

**Comment by charles-lunarg** [comment] 2019-11-21 22:43
This is indeed caused by separate printing of the head and body.
The simplest solution would be to keep the output lock held after printing the head while calling into the driver, then releasing it after printing the body.
The solutions you provided do work but have specific limitations.
a) There'd still be incorrect output for non-file outputs and I'd prefer a solution that works for both.
b) It is redundant with printing everything after the call to the driver. Currently, api_dump prints the header, calls into the driver, then prints the body. The reason was in case the driver crashed, you'd know which function caused the crash instead of only the previous (successful) api call. Saving a buffer suffers the same problem, as a crash means you can't print the header. 

The only issue with the simple solution would that any call into api_dump is serialized. Granted, any output that api_dump did before the change to printing header and body separately was serial, but now it encompasses the entire call, not just the output. 
I feel that it is an acceptable cost, since api_dump's printing already slows any running program.

**Comment by charles-lunarg** [comment] 2019-12-03 17:52
I have created PR #934 which solves the issue by locking for the duration of the call to the ICD.

**Comment by charles-lunarg** [comment] 2019-12-09 20:52
As the PR was merged, I will close this thread unless further issues are discovered.

**Comment by charles-lunarg** [comment] 2019-12-11 17:27
@dor666 I am closing the issue by the end of the week as the PR was merged unless there still are issues.

**Closed** 2019-12-11 18:25 UTC
