### ISSUE TITLE
vkconfig3: GUI spacing issues on macOS

### ISSUE THREAD

**Issue by richard-lunarg** [LunarG/VulkanTools#2188] opened 2024-11-22 16:41 UTC
The list of layers shown here still has spacing issues. Are you hard coding these values?

<img width="1037" alt="image" src="https://github.com/user-attachments/assets/9481b8b7-09c5-4760-9101-de08a736569d">

**Comment by christophe-lunarg** [comment] 2024-11-26 17:31
I think the issue is that the tree items are smaller than the control combobox but the combobox are resize based on the tree item size with `setGeometry`. I'll investigate.

**Comment by christophe-lunarg** [comment] 2024-11-28 15:59
This issue is resolved by https://github.com/LunarG/VulkanTools/pull/2205

**Closed by christophe-lunarg** 2024-11-28 15:59 UTC
Labels: bug, P3, OS - Apple, OS - platform independent, Project - vkconfig3
