### ISSUE TITLE
api_dump layer does not recognize extended image formats

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#634] opened 2018-09-26 21:01 UTC
Using VK_FORMAT_G8_B8R8_2PLANE_420_UNORM in vkCreateImage, I see:

       format:                         VkFormat = UNKNOWN (1000156003)

Looking up the enumeration would be useful

**Comment by charles-lunarg** [comment] 2019-05-15 18:05
Extensions which add enum values to core enums are not accounted for. 
This issue is identical to #742, with likely the same fix.

**Comment by charles-lunarg** [comment] 2019-05-15 18:07
Confirming that the issue is the same, and fixed by #815

**Closed** 2019-07-02 14:59 UTC
Labels: apidump
