### ISSUE TITLE
windows via has inconsistent path conventions

### ISSUE THREAD

**Issue by lunarpapillo** [LunarG/VulkanTools#747] opened 2019-03-01 22:26 UTC
Windows Via (inside vkconfig) shows the **Exe Directory** as **C:/VulkanSDK/1.1.101.0/Bin** (which is Linux pathname convention), but the **Current Directory** as **C:\VulkanSDK\1.1.101.0\Bin** (the Windows pathname convention).

Both should be using the Windows pathname convention.

I don't think this is important enough to hold up this SDK.

**Comment by davidlunarg** [comment] 2022-08-09 20:40
Duplicate of https://github.com/LunarG/VulkanTools/issues/912

**Closed** 2022-08-09 20:41 UTC
Labels: Project - vkVIA
