### ISSUE TITLE
Examples at https://github.com/McNopper/Vulkan don't trace/replay

### ISSUE THREAD

**Issue by Tony-LunarG** [LunarG/VulkanTools#45] opened 2016-05-19 23:03 UTC
I've tried Examples 4-6 (Linux + Mesa) and they all trace but they all playback only background color.  They call vkFlushMappedMemoryRanges so it's probably not the persistently mapped memory issue.

**Comment by ardaLunarG** [comment] 2016-08-04 22:30
The issue was the application was doing memMap, flush and unmap, but it changes buffers between flush and unmap. Our traces ignores changes in memory if it is already flushed.

With following change it works fine, which I capture changes even they are flushed.

VKTRACER_EXPORT VKAPI_ATTR void VKAPI_CALL __HOOKED_vkUnmapMemory(
 ....
    entry = find_mem_info_entry(memory);
    if (entry && entry->pData != NULL)
    {
        //if (!entry->didFlush)
        //{
            // no FlushMapped Memory
            siz = (size_t)entry->rangeSize;
        //}
    }
    CREATE_TRACE_PACKET(vkUnmapMemory, siz);

Main cause of this bug filed within GitHub Issue #61.
Thus I close this bug and follow up within #61.

**Comment by ardaLunarG** [comment] 2016-08-04 22:31
Duplicate of #61

**Closed by ardaLunarG** 2016-08-04 22:31 UTC
Labels: bug, enhancement
