### ISSUE TITLE
vkconfig: changing the preset value will scroll settings panel to the top

### ISSUE THREAD

**Issue by johnzupin** [LunarG/VulkanTools#1300] opened 2020-12-28 22:56 UTC
Changing the VK_LAYER_LUNARG_device_simulation preset value causes the portability settings panel to scroll to the top

![devsim_preset_selection](https://user-images.githubusercontent.com/3836693/103247754-382ca680-4925-11eb-942b-2a1fb23adb0d.gif)

**Comment by christophe-lunarg** [comment] 2021-01-04 13:01
Another difficult issue to resolve... The issue is that the GUI code design blend creation of the UI and initialization of the UI.

Here when the preset is changed, the settings needs to be updated so the entire tree is recreated so the scrollbar position is lost...

**Comment by christophe-lunarg** [comment] 2021-04-23 12:50
This issue is fixed with PR #1463

**Closed by christophe-lunarg** 2021-04-23 12:50 UTC
Labels: OS - platform independent, P3, Project - vkconfig, enhancement
