### ISSUE TITLE
Cannot trace Subnautica

### ISSUE THREAD

**Issue by Evernow** [LunarG/VulkanTools#989] opened 2020-04-16 10:48 UTC
Hello there!

Have been trying to trace Subnautica to help troubleshoot a hang that occurs with Navi, but the game crashes shortly after opening, this is the output of the command window: 

https://gist.github.com/Evernow/c9d1e73dd1a9203e18f81ff625861b18

**Comment by davidlunarg** [comment] 2020-04-16 14:40
I can't tell why it's crashing from the output.

vktrace is in the process of being deprecated, to be replaced with gfxreconstruct (https://github.com/LunarG/gfxreconstruct). Could you see if the same problem occurs with gfxreconstruct?

**Comment by Evernow** [comment] 2020-04-16 15:23
> I can't tell why it's crashing from the output.
> 
> vktrace is in the process of being deprecated, to be replaced with gfxreconstruct (https://github.com/LunarG/gfxreconstruct). Could you see if the same problem occurs with gfxreconstruct?

Sorry but I don't understand the documentation on usage, how does one trace a steam game with that?

**Comment by davidlunarg** [comment] 2020-04-16 15:58
Tracing with gfxreconstruct is very similar to tracing using the VK_LAYER_LUNARG_vktrace layer. First build gfxreconstruct for your platform (see https://github.com/LunarG/gfxreconstruct/blob/master/BUILD.md). Then create a trace as described in https://github.com/LunarG/gfxreconstruct/blob/master/layer/USAGE_desktop.md

**Comment by Evernow** [comment] 2020-04-16 17:10
> Tracing with gfxreconstruct is very similar to tracing using the VK_LAYER_LUNARG_vktrace layer. First build gfxreconstruct for your platform (see https://github.com/LunarG/gfxreconstruct/blob/master/BUILD.md). Then create a trace as described in https://github.com/LunarG/gfxreconstruct/blob/master/layer/USAGE_desktop.md

That seems to have failed to build 

```
make[2]: Entering directory '/run/media/daniel/O/gfxrecon take 2/gfxreconstruct/build'
CMake Error: File /run/media/daniel/O/gfxrecon/ take/ 2/gfxreconstruct/layer/json/VK_LAYER_LUNARG_gfxreconstruct.json.in does not exist.
CMake Error at generator.cmake:1 (configure_file):
  configure_file Problem configuring file


make[2]: *** [layer/CMakeFiles/VkLayer_gfxreconstruct_json.dir/build.make:74: layer/CMakeFiles/VkLayer_gfxreconstruct_json] Error 1
make[2]: Leaving directory '/run/media/daniel/O/gfxrecon take 2/gfxreconstruct/build'
make[1]: *** [CMakeFiles/Makefile2:485: layer/CMakeFiles/VkLayer_gfxreconstruct_json.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 78%] Linking CXX static library libgfxrecon_decode.a
make[2]: Leaving directory '/run/media/daniel/O/gfxrecon take 2/gfxreconstruct/build'
[ 78%] Built target gfxrecon_decode
make[1]: Leaving directory '/run/media/daniel/O/gfxrecon take 2/gfxreconstruct/build'
make: *** [Makefile:101: all] Error 2
```

**Comment by davidlunarg** [comment] 2020-04-16 18:23
There are spaces in the path for you gfxreconstruct build. I suspect the gfxreconstruct cmake files don't handle spaces in paths very well. Could you try again using a path without spaces?

The way you describe to create a trace of a using vktrace is the way I have often done it. Start the server (vktrace without a -p option) on one terminal, and run the app from another terminal with the vktrace layer enabled. Note that gfxrecon doesn't use the server/layer model - there isn't a server and the layer will create and write to the trace file directly.

**Comment by Evernow** [comment] 2020-04-16 18:48
> There are spaces in the path for you gfxreconstruct build. I suspect the gfxreconstruct cmake files don't handle spaces in paths very well. Could you try again using a path without spaces?
> 
> The way you describe to create a trace of a using vktrace is the way I have often done it. Start the server (vktrace without a -p option) on one terminal, and run the app from another terminal with the vktrace layer enabled. Note that gfxrecon doesn't use the server/layer model - there isn't a server and the layer will create and write to the trace file directly.

Thank you, that was indeed it there can't be a space in the directory. I just tested it and i believe i built it correctly because it created the gfxrecon capture in the game's directory, but sadly it crashed moments after launching like vktrace. 

In the command window it kept spamming "type known not a basic type"

To confirm the commands I ran were in order:

export VK_LAYER_PATH=//run/media/daniel/O/gfxreconstruct/gfxreconstruct/build/layer:$VK_LAYER_PATH

export VK_INSTANCE_LAYERS=VK_LAYER_LUNARG_gfxreconstruct

steam steam steam://rungameid/264710

This was the file I got in the game's directory: 


[gfxrecon_capture_20200416T144213.gfxr.zip](https://github.com/LunarG/VulkanTools/files/4489185/gfxrecon_capture_20200416T144213.gfxr.zip)

**Comment by davidlunarg** [comment] 2020-04-16 21:20
You can run the capture file through build/tools/gfxrecon-toascii to get a list all the api calls that were captured in the trace. And then run the app with the api_dump layer enabled. By comparing the two lists, you might be able to figure out which api call the app died in or near.

**Comment by Evernow** [comment] 2020-04-17 03:54
> You can run the capture file through build/tools/gfxrecon-toascii to get a list all the api calls that were captured in the trace. And then run the app with the api_dump layer enabled. By comparing the two lists, you might be able to figure out which api call the app died in or near.

Alright, ran this

[daniel@daniel-pc ~]$ /run/media/daniel/O/gfxreconstruct/gfxreconstruct/build/tools/toascii/gfxrecon-toascii /run/media/daniel/O/SteamLibrary/steamapps/common/Subnautica/gfxrecon_capture_20200416T144213.gfxr 
[gfxrecon] WARNING - Incomplete block at end of file

And got this output: 
[gfxrecon_capture_20200416T144213.txt](https://github.com/LunarG/VulkanTools/files/4490703/gfxrecon_capture_20200416T144213.txt)

Apologies but how do I do the api_dump layer?

**Comment by davidlunarg** [comment] 2020-04-17 14:40
> Apologies but how do I do the api_dump layer?

See https://vulkan.lunarg.com/doc/sdk/1.2.135.0/windows/api_dump_layer.html

**Comment by Evernow** [comment] 2020-04-17 17:37
> The warning is not unexpected. This often happens when a program dies prematurely and the trace layer is not able to write the full block of data for the last api call.
> 
> > Apologies but how do I do the api_dump layer?
> 
> See https://vulkan.lunarg.com/doc/sdk/1.2.135.0/windows/api_dump_layer.html

Sorry for late reply and thanks for helping me!

I believe I did it correctly, however it was not outputting to a file similar to before but just spamming the command window, I put > randomlog.txt at the end of the command to run the steam game to capture it all into one text file (extracted it is an insane 450mb): 


https://drive.google.com/file/d/1hCakmLaAJjq6nD_c6XorenrRGM8tZd8x/view?usp=sharing

I'm not sure where it stops, as the only ones near the end of the output when it crashes are ones repeated constantly, not sure where to go from here

**Comment by davidlunarg** [comment] 2020-04-17 21:00
I looked at the api dump and the trace files you provided. This app has multiple threads with Vulkan api calls being made from many of them. Inserting a trace layer or an api_dump layer results in the sequence of calls being different for the two layers. Thus it is difficult to determine when during tracing that the app is crashing.

This issue will likely not be addressed in vktrace since it is being replaced with gfxreconstruct.

We can look at the issue and try to determine the cause in gfxreconstruct. Could you submit an issue in the gfxreconstruct project? Please include OS/hardware/driver information.

**Closed by davidlunarg** 2020-04-17 21:00 UTC
