### ISSUE TITLE
writes to device memory allocated with VK_MEMORY_PROPERTY_HOST_COHERENT_BIT are not captured ?

### ISSUE THREAD

**Issue by mccaffrey-jonathan** [LunarG/VulkanTools#3] opened 2016-02-18 21:39 UTC
https://github.com/LunarG/VulkanTools/blob/master/vktrace/src/vktrace_layer/vktrace_lib_trace.cpp traces data written to mapped memory in __HOOKED_vkUnmapMemory and __HOOKED_vkFlushMappedMemoryRanges .  However, allocations made with VK_MEMORY_PROPERTY_HOST_COHERENT_BIT may be written by the host and read by the device with no synchronization other than  the implicit synchronization of vkQueueSubmit, and without vkUnmapMemory'ing the vkDeviceMemory .  This could allow writes that affect the rendered result (for example, to a uniform buffer) to not be captured by the tracing layer .

One way to solve this would be for the layer to prevent heaps from allowing allocations with VK_MEMORY_PROPERTY_HOST_COHERENT_BIT ?

**Comment by olvaffe** [comment] 2016-02-18 22:00
The spec requires at least one memory type that is host visible and host coherent, IIRC.

**Comment by mccaffrey-jonathan** [comment] 2016-02-18 22:44
So it does, at https://www.khronos.org/members/login/sandbox/vulkan/wsi/xhtml/vkspec.html#memory-device

It is guaranteed that there is at least one memory type that has its propertyFlags with the VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT bit set and the VK_MEMORY_PROPERTY_HOST_COHERENT_BIT bit set.

**Comment by mccaffrey-jonathan** [comment] 2016-02-19 03:04
For the vkQueueSubmit implicit memory barrier at least, I think it would be correct but slow , to walk all mapped memory ranges of vkDeviceMemory allocated with VK_MEMORY_PROPERTY_HOST_COHERENT_BIT at submit time, and record changed ranges .

It may also be necessary to walk the mapped ranges on vkSetEvent .  I think it is allowed for the device to read data that was written by the host after the command buffer was submitted, if the command buffer contains a vkCmdWaitEvents which is signalled by the host after the write completes, and then  pipeline barrier from a source of VK_ACCESS_HOST_WRITE_BIT and VK_PIPELINE_STAGE_HOST_BIT .

**Comment by jon-lunarg** [comment] 2016-02-19 05:14
Thanks for alerting us to these issues.

**Comment by davidlunarg** [comment] 2016-08-11 23:06
This is a duplicate of VulkanTools issue #69. Closing.

**Closed by davidlunarg** 2016-08-11 23:06 UTC
Labels: enhancement
