### ISSUE TITLE
Update vkVia Executable:Vulkan API Version to be correct

### ISSUE THREAD

**Issue by charles-lunarg** [LunarG/VulkanTools#1650] opened 2022-02-14 17:29 UTC
Currently its hardcoded but with 1.3 and future minor revisions, it would be best to update it so that it 'knows' which header version it was compiled with.

**Comment by davidlunarg** [comment] 2022-08-15 15:58
Duplicate of https://github.com/LunarG/VulkanTools/issues/1713

**Closed by davidlunarg** 2022-08-15 15:58 UTC
Labels: bug, Project - vkVIA
