### ISSUE TITLE
xcb-keysyms not found for 32-bit build

### ISSUE THREAD

**Issue by c-charles1** [LunarG/VulkanTools#371] opened 2018-01-03 20:46 UTC
I am trying to build 32-bit targets on a 64-bit Ubuntu 16.04 platform.

I am able to build the Vulkan-LoaderAndValidationLayers repo using the instructions there, i.e. I set these:

export ASFLAGS=--32
export CFLAGS=-m32
export CXXFLAGS=-m32
export PKG_CONFIG_LIBDIR=/usr/lib/i386-linux-gnu

But when I try the same for the VulkanTools repo, I get this:

-- Checking for one of the modules 'xcb-keysyms'
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:578 (message):
  None of the required 'xcb-keysyms' found
Call Stack (most recent call first):
  vktrace/vktrace_layer/CMakeLists.txt:6 (pkg_search_module)

I do have the i386 versions of libxcb-keysyms1 and libxcb-keysyms1-dev installed.

I get similar results on CentOS 7.4.

**Comment by johnzupin** [comment] 2018-01-03 23:20
I can recreate this problem on my Ubuntu 16.04 box. Not sure why it's happening yet, currently looking into it.

**Comment by johnzupin** [comment] 2018-01-04 00:09
I think problem is at vktrace/vktrace_layer/CMakeLists.txt on line 6:

```
cmake_minimum_required(VERSION 2.8)

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
   if (BUILD_WSI_XCB_SUPPORT)
       set(ENV{VULKAN_WSI} "Xcb")
       pkg_search_module(XCB-KEYSYMS REQUIRED xcb-keysyms) #THIS LINE HERE
   elseif (BUILD_WSI_XLIB_SUPPORT)
       set(ENV{VULKAN_WSI} "Xlib")
   elseif (BUILD_WSI_WAYLAND_SUPPORT)
       set(ENV{VULKAN_WSI} "Wayland")
   else()
       # Mir WSI Case
       set(ENV{VULKAN_WSI} "Mir")
   endif()
endif()
```
I'm not sure which function is correct but if i change "pkg_search_module" to "find_library" it seems to work. Although, running make will fail when trying to link vkreplay32 - not sure if this is related or a new problem. 

I need to read up on some cmake docs...

**Comment by johnzupin** [comment] 2018-01-04 18:03
The problem is at:  VulkanTools/vktrace/vktrace_layer/CMakeLists.txt, line 6.

```
cmake_minimum_required(VERSION 2.8)

if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
   if (BUILD_WSI_XCB_SUPPORT)
       set(ENV{VULKAN_WSI} "Xcb")
       pkg_search_module(XCB-KEYSYMS REQUIRED xcb-keysyms) #this line here
   elseif (BUILD_WSI_XLIB_SUPPORT)
       set(ENV{VULKAN_WSI} "Xlib")
   elseif (BUILD_WSI_WAYLAND_SUPPORT)
       set(ENV{VULKAN_WSI} "Wayland")
   else()
       # Mir WSI Case
       set(ENV{VULKAN_WSI} "Mir")
   endif()
endif()
```
I'll look into this. Linking @davidlunarg and @joey-lunarg to this, let me know if you guys have any input.

**Comment by johnzupin** [comment] 2018-01-04 18:05
I think pkg_search_module function should be find_library function

**Comment by c-charles1** [comment] 2018-01-04 22:32
Changing pkg_search_module to find_library makes cmake happy. But then there's an error linking vkreplay32:

[ 93%] Linking CXX executable ../vkreplay32
../../loader/libvulkan.so.1.0.65: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[2]: *** [vktrace/vkreplay32] Error 1
make[1]: *** [vktrace/vktrace_replay/CMakeFiles/vkreplay.dir/all] Error 2
make: *** [all] Error 2

**Comment by c-charles1** [comment] 2018-01-05 17:04
I realize the link error could be a separate issue from the pkg_search_module error. But it might be a problem with flags. Running "grep -R m32" in dbuild/vktrace returns nothing, whereas m32 makes it through to the other directories in dbuild, i.e. demos, layers, loader, libs, etc.

**Comment by johnzupin** [comment] 2018-01-06 00:23
Yeah there is some funky cmake logic at https://github.com/LunarG/VulkanTools/blob/master/vktrace/CMakeLists.txt on line 130.

I changed the conditional from:
```
if ((NOT MSVC) AND (NOT BUILD_X64) AND (CMAKE_SIZEOF_VOID_P EQUAL 8))
    set(CMAKE_CXX_FLAGS_LIST "${CMAKE_CXX_FLAGS_LIST} -m32")
    set(CMAKE_EXE_LINK_FLAGS_LIST "${CMAKE_EXE_LINK_FLAGS_LIST} -m32")
    set(CMAKE_SHARED_LINK_FLAGS_LIST "${CMAKE_SHARED_LINK_FLAGS_LIST} -m32")

    set_property(GLOBAL PROPERTY FIND_LIBRARY_USE_LIB64_PATHS OFF)
    set(CMAKE_SYSTEM_LIBRARY_PATH /lib32 /usr/lib32 /usr/lib/i386-linux-gnu /usr/local/lib32)
    set(CMAKE_IGNORE_PATH /lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib64 /usr/local/lib)
endif()
```

to

```
if ((NOT MSVC) AND (NOT BUILD_X64))
    set(CMAKE_CXX_FLAGS_LIST "${CMAKE_CXX_FLAGS_LIST} -m32")
    set(CMAKE_EXE_LINK_FLAGS_LIST "${CMAKE_EXE_LINK_FLAGS_LIST} -m32")
    set(CMAKE_SHARED_LINK_FLAGS_LIST "${CMAKE_SHARED_LINK_FLAGS_LIST} -m32")

    set_property(GLOBAL PROPERTY FIND_LIBRARY_USE_LIB64_PATHS OFF)
    set(CMAKE_SYSTEM_LIBRARY_PATH /lib32 /usr/lib32 /usr/lib/i386-linux-gnu /usr/local/lib32)
    set(CMAKE_IGNORE_PATH /lib /usr/lib /usr/lib/x86_64-linux-gnu /usr/lib64 /usr/local/lib)
endif()
```

and it compiled. I haven't done any testing yet. I'll do some testing and create a pull request soon. Let me know if this worked for you.

**Comment by johnzupin** [comment] 2018-01-08 18:11
Pull Request created #374

**Comment by johnzupin** [comment] 2018-01-15 20:14
Pull Request Merged. Closing this out.

**Closed by johnzupin** 2018-01-15 20:14 UTC
